### ISSUE TITLE
[QUESTION] How to begin transaction, use 0.9.3 r2dbc-mysql

### ISSUE THREAD

**Issue by theWangs** [asyncer-io/r2dbc-mysql#137]
jdk 1.8
springboot 2.7.14
r2dbc-mysql 0.9.3
follow example：
![image](https://github.com/asyncer-io/r2dbc-mysql/assets/31178945/3a83a6ac-f0d9-4e7d-91dd-36d33248a095)
and error mes:  Cannot resolve method 'then' in 'Publisher'
now ,how can i begin a transcation?

**Comment by theWangs** [comment]
![image](https://github.com/asyncer-io/r2dbc-mysql/assets/31178945/97beb4a1-5799-4ae1-8a86-f2069cb08256)
![image](https://github.com/asyncer-io/r2dbc-mysql/assets/31178945/4e938ebe-a3ce-4b8c-94f5-d520fd44810f)
miss commit
so, please tell me how to do it....
This is my first time use reactor java

**Comment by jchrys** [comment]
Hello, @theWangs.
Thank you for the question!

In the first screenshot, when you invoke the line `connection.beginTransaction().then(Something)`, it is valid when `connection.beginTransaction()` returns a Mono<?> type.

There are various ways to achieve this, but a simple method is to use `MySqlConnection connection = (MySqlConnection) conMono.block()` instead of `Connection connection = conMono.block()`

If you have any further questions, please feel free to ask.

**Comment by theWangs** [comment]
Thanks a lot！ this has been confusing me for days
