### ISSUE TITLE
[QUESTION] How about removing `socketTimeout`?

### ISSUE THREAD

**Issue by mirromutth** [asyncer-io/r2dbc-mysql#222]
## Summary

For now, `socketTimeout` has been marked as deprecated since 1.0.1, and it will not actually work. Is time to remove it. Any idea?

## Detailed description

There are two solutions:

1. Just remove it completely. It can be removed since 1.1.1
2. Remove property `socketTimeout` in `MySqlConnectionConfiguration`, and keep `Option` and method `socketTimeout()`, then remove it completely since 1.2.x
   - All source/test files should have no code about the `socketTimeout`, except `MySqlConnectionConfiguration` and `MySqlConnectionFactoryProvider`

**Comment by jchrys** [comment]
Thank you for bringing this to attention. I also recommend removing it entirely for simplicity and clarity(especially since we've been writing warning logs that `Socket timeout is not supported by the underlying connection and will be ignored`). Once the changes are merged, we could aim to include this update in the 1.1.0 release. How does that sound?
