### ISSUE TITLE
[bug]align with`RowMetaData#getColumnMetadata(String)` specification

### ISSUE THREAD

**Issue by jchrys** [asyncer-io/r2dbc-mysql#244]
**Describe the bug**
The specification states 
```
@param name the name of the column.  
Column names are case-insensitive.  
When a get method contains several columns with same name, 
then the value of the >> first matching column << will be returned
```
However, the current behavior does not align with the specification.

**To Reproduce**
```Java
connection.createStatement(SELECT 1 as t, 2 as t, 3 as t).execute()
                .flatMap(result -> Mono.from(result.map((row, metadata) -> row.get("t", Integer.class))))
                .doOnNext(System.out::println);
```
Prints `2`

**Expected behavior**
It should print `1`

**Screenshots**

**Additional context**

**Comment by mirromutth** [comment]
It is caused by [`MySqlNames.binarySearch`](https://github.com/asyncer-io/r2dbc-mysql/blob/trunk/r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/MySqlNames.java#L50) and [Sort Comparator](https://github.com/asyncer-io/r2dbc-mysql/blob/trunk/r2dbc-mysql/src/main/java/io/asyncer/r2dbc/mysql/ColumnNameSet.java#L44)

The searching should do something like C++ [`std::lower_bound`](https://en.cppreference.com/w/cpp/algorithm/lower_bound) does.

The sorting should consider about index.

**Comment by jchrys** [comment]
@mirromutth 
I found that in our current implementation, enclosing a name in backticks causes case-sensitive mode. However, I'm considering removing this feature, since queries like ```SELECT `t` from (SELECT 1 as `T`) c``` work in a case-insensitive manner(+mariadb-r2dbc seems not  support backtick). What are your thoughts on this?

**Comment by mirromutth** [comment]
Yep, we can just remove case-sensitive mode.

It was a feature for [`RowMetadata.contains`](https://github.com/r2dbc/r2dbc-spi/blob/v1.0.0.RELEASE/r2dbc-spi/src/main/java/io/r2dbc/spi/RowMetadata.java#L58)

> Implementations may allow escape characters to enforce a particular mode of comparison when querying for presence/absence of a column.

But only the javadoc for `contains` describes it, I don't see any description about this in the specification: https://r2dbc.io/spec/1.0.0.RELEASE/spec/html/#columnmetadata
