### ISSUE TITLE
Handling int<lenenc> values greater than 2^63-1 in MySQL OKPackets and related packets

### ISSUE THREAD

**Issue by jchrys** [asyncer-io/r2dbc-mysql#39]
## Issue Description

It has come to our attention that MySQL's OKPackets and other packets containing `int<lenenc>` types may potentially have values greater than 2^63-1. As per the MySQL documentation, [`int<lenenc>`](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_basic_dt_integers.html#sect_protocol_basic_dt_int_le) supports such values.

## Current Implementation

Our current implementation does not take this into account, and we need to address this issue to ensure proper handling of `int<lenenc>` values exceeding 2^63-1.

## Impact on Real-world Usage

It is worth noting that this issue does not have a significant impact on real-world usage. Nonetheless, when converting the value to a string representation, it might be presented as a negative number.

## Proposed Solution

To enhance the accuracy and reliability of our implementation, we need to implement a patch that properly handles `int<lenenc>` values exceeding 2^63-1.

**Comment by mirromutth** [comment]
This is caused by `VarIntUtils.readVarInt` trying to read 8 bytes and returning it directly as an integer for performance reasons, which should theoretically be wrapped with an object (such as writing an `UnsignedLong` or using a `BigInteger`).

However, this lower-level decoding operation may affect performance if using wrapper classes. Maybe add some code comments to inform the developer how the return value should be used instead of using a wrapper class.

**Comment by jchrys** [comment]
Resolved by @mirromutth (https://github.com/asyncer-io/r2dbc-mysql/pull/161, #168 )
